In [2]:
import tensorflow as tf

In [3]:
print(tf.version)

<module 'tensorflow._api.v2.version' from 'C:\\Users\\Mani\\Sample\\env\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


In [4]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [5]:
print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>


In [6]:
print(number),print(floating)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


(None, None)

### rank

In [8]:
rank1_tensor = tf.Variable(["test","ok","shasti"],tf.string)
rank2_tensor = tf.Variable([["test","ok","pls"],["test","ok","pls"],["hava","this","for"]],tf.string)

In [9]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [10]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [11]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [12]:
rank2_tensor.shape

TensorShape([3, 3])

In [13]:
tensor1 = tf.ones([1,2,3])

In [14]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [19]:
tensor2=tf.reshape(tensor1, (2,3,1))
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>